### ISSUE TITLE
❓ [Question]: Problem with bootloader

### ISSUE THREAD

**Issue by oddeye** [MrE8065/MyDotfiles#1]
### Question Description

I am loving your work, i tried fresh install of minimal arch + hyprland. The installation script went smoothly, but it doesn`t boot right. Could it be problem with my default systemmd-boot? At the moment it just goes into shell and when I manually start hyperland, it loads the default autogenerated config. I am bit lost, to be honest.

**Comment by MrE8065** [comment]
I use grub, so I don't know if is a problem with systemd 😅. By the way, did you installed the dotfiles with the latest commits? I fixed some errors and maybe it's that.

**Comment by oddeye** [comment]
I will try another install with the new dotfiles. Thanks for the help 👍

**Comment by oddeye** [comment]
It seems that the problem persisted. New install of minimal arch, after that hyperland and right after that your install.sh script. It went fine, only error I got was something about wallpaper, but the script kept going, until it was finished. 

This time I tried grub instead, didn`t help. After reboot I have default login screen. When I log in and start hyprland, it has autogenerated config.

It feels like I am forgetting something, but I am not sure what.

**Comment by MrE8065** [comment]
That's weird... I'm gonna take a look

**Comment by MrE8065** [comment]
I fixed it 😀. The config folder was not being copied correctly. Also, the login screen theme is for sddm, so I added another step where the script asks if you want to install the theme, in case you are not using sddm as the display manager

**Comment by oddeye** [comment]
Hi and thank you for your patience :) ! Tried it again with latest install.sh. and found the .config folder inside .config folder 
-> **/home/ffrk/.config/.config** Atleast I have got the sddm :D
